FROM node:22-alpine

WORKDIR /app

# Accept build-time envs
ARG VITE_SERVER_URL

# Set environment variables for Vite build
ENV VITE_SERVER_URL=$VITE_SERVER_URL

# Copy package files first (better caching)
COPY package*.json .  

# Install deps
RUN npm install

# Copy the rest of the application code
COPY . .  

# Build the Vite app
RUN npm run build

# Start the preview server
CMD ["npm", "run", "preview"]
